server:
    port: 8888

spring:
    application:
        name: configsrv

    profiles:
        active: native, dev

    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/config-repo/{profile}
