server:
    port: 8246

spring:
    datasource:
        url : jdbc:mysql://localhost:3306/bjdj?useSSL=false
        username : root
        password : 111333
        driverClassName : com.mysql.jdbc.Driver

    # 以下两项为404抛出NoHandlerFoundException异常方便统一处理
    resources:
        add-mappings: false
    mvc:
        throw-exception-if-no-handler-found: true

    output:
        ansi:
            enabled: always

logging:
    level:
        com.ethan.stage: debug

strConfig: nikyo
