server:
  port: 8888

spring:
  output:
    ansi:
      enabled: always

  redis:
    host: 127.0.0.1
    port: 6379
    password: null

logging:
  level:
    com.ethan.stage: debug
    #org.springframework.security: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
