server:
    port: 8501

security:
  oauth2:
    client:
      grantType: client_credentials
      clientId: client2
      clientSecret: 123456
    resource:
      tokenInfoUri: http://localhost:8888/oauth/check_token
